-- MySQL Script generated by MySQL Workbench
-- Wed Jun 21 20:47:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `puntos` INT NOT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`Desafios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Desafios` (
  `id` VARCHAR(16) NOT NULL,
  `Contenido` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`Acepta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Acepta` (
  `Usuario_email` VARCHAR(255) NOT NULL,
  `Desafios_id` VARCHAR(16) NOT NULL,
  `Status` INT NOT NULL,
  PRIMARY KEY (`Usuario_email`, `Desafios_id`),
  INDEX `fk_Usuario_has_Desafios_Desafios1_idx` (`Desafios_id` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Desafios_Usuario_idx` (`Usuario_email` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Desafios_Usuario`
    FOREIGN KEY (`Usuario_email`)
    REFERENCES `mydb`.`Usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Desafios_Desafios1`
    FOREIGN KEY (`Desafios_id`)
    REFERENCES `mydb`.`Desafios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Formulario` (
  `Usuario_email` VARCHAR(255) NOT NULL,
  `gusto1` VARCHAR(255) NOT NULL,
  `gusto2` VARCHAR(45) NOT NULL,
  `gusto3` VARCHAR(45) NOT NULL,
  `gusto4` VARCHAR(45) NOT NULL,
  `gusto5` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Usuario_email`),
  CONSTRAINT `fk_Formulario_Usuario1`
    FOREIGN KEY (`Usuario_email`)
    REFERENCES `mydb`.`Usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
